name:                graphlib-hs
version:             0.1.0.1
github:              "mskmysht/graphlib-hs"
license:             BSD3
author:              "Masaaki Miyashita"
maintainer:          "m.mysht118@gmail.com"
copyright:           "2019 Masaaki Miyashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mskmysht/graphlib-hs#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- vector
- hashtables
- unordered-containers
- hxt
- mtl
- transformers
- witherable
- hmatrix
- criterion
- sfmt
- primitive
- pointed

library:
  source-dirs: src

executables:
  graphlib-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphlib-hs

tests:
   graphlib-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphlib-hs
